# Generated by Django 4.1.4 on 2022-12-23 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_orderitems_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitems',
            name='quantity',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
